# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from data_module.models.base_model_ import Model
from data_module import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file_name: str=None, label: str=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param file_name: The file_name of this Body.  # noqa: E501
        :type file_name: str
        :param label: The label of this Body.  # noqa: E501
        :type label: str
        """
        self.swagger_types = {
            'file_name': str,
            'label': str
        }

        self.attribute_map = {
            'file_name': 'fileName',
            'label': 'label'
        }
        self._file_name = file_name
        self._label = label

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_name(self) -> str:
        """Gets the file_name of this Body.


        :return: The file_name of this Body.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this Body.


        :param file_name: The file_name of this Body.
        :type file_name: str
        """

        self._file_name = file_name

    @property
    def label(self) -> str:
        """Gets the label of this Body.


        :return: The label of this Body.
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label: str):
        """Sets the label of this Body.


        :param label: The label of this Body.
        :type label: str
        """

        self._label = label
